// <autogenerated />
using CommonData.VO;
using Microsoft.AspNetCore.Components;
using System.ComponentModel.DataAnnotations;
using WhatsAppBusiness;
using WhatsAppData.VO.WhatsApp;
using WhatsAppFDM;

namespace BrilliantWhatsAppWeb.Components.Pages;

public partial class WhatsAppTenantDetail
{

    [Parameter]
    public Guid TenantId { get; set; }

    private WhatsAppTenantFDM _fdm { get; set; } = new WhatsAppTenantFDM();

    private WhatsAppTenantVO _whatsAppTenant = new WhatsAppTenantVO();
    private bool showToken = false;
    private string notificationMessage = "";
    private string notificationClass = "";

    protected override async Task OnInitializedAsync()
    {
        try
        {
            await BeginEdit();
        }
        catch (Exception ex)
        {
            ShowNotification($"Error loading tenant: {ex.Message}" , "error");
        }
    }

    private async Task BeginEdit()
    {
        if (TenantId == Guid.Empty)
        {
            // Get a new instance for creation
            _whatsAppTenant = await _fdm.GetNew();
        }
        else
        {
            // Load existing tenant
            _whatsAppTenant = await _fdm.GetBy(TenantId);
        }
    }

    private async Task HandleValidSubmit()
    {
        try
        {
            await EndEdit();
            NavManager.NavigateTo("/whatsapp-tenants");
        }
        catch (Exception ex)
        {
            ShowNotification($"Error saving tenant: {ex.Message}" , "error");
        }
    }

    private async Task EndEdit()
    {
        // Save using FDM
        await _fdm.Persist(_whatsAppTenant);
    }

    private void GoBack()
    {
        NavManager.NavigateTo("/whatsapp-tenants");
    }

    private void ToggleTokenVisibility() => showToken = !showToken;

    private void ShowNotification(string message , string type)
    {
        notificationMessage = message;
        notificationClass = type == "error" ? "error" : "success";
        StateHasChanged();
        Task.Delay(4000).ContinueWith(_ =>
        {
            notificationMessage = "";
            InvokeAsync(StateHasChanged);
        });
    }
}