// <autogenerated />
using CommonData.VO;
using Microsoft.AspNetCore.Components;
using Microsoft.JSInterop;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Threading;
using WhatsAppBusiness;
using WhatsAppData.DAO;
using WhatsAppData.VO.WhatsApp;
using WhatsAppFDM;

namespace BrilliantWhatsAppWeb.Components.Pages;

public partial class WhatsAppTenantDetail
{

    [Parameter]
    public Guid TenantId { get; set; }

    [Inject]
    private IJSRuntime JS { get; set; } = default!;

    private WhatsAppTenantFDM _fdm { get; set; } = new WhatsAppTenantFDM();

    private WhatsAppTenantVO _whatsAppTenant = new WhatsAppTenantVO();
    private bool showToken = false;
    private string notificationMessage = "";
    private string notificationClass = "";

    // Field editability controls (progressive form)
    private bool _isEditingExisting;
    private bool _canEditContactName;
    private bool _canEditPhoneNumberId;
    private bool _canEditBusinessAccountId;
    private bool _canEditAccessToken;

    // Read-only lookups that were auto-filled from the database
    private bool _waIdFound;
    private bool _businessAccountFound;

    // Debounce cancellation for the WA ID auto-fetch, so typing a number doesn't
    // trigger an out-of-order database lookup for an older/partial value.
    private CancellationTokenSource _waIdSearchCts = new CancellationTokenSource();

    protected override async Task OnInitializedAsync()
    {
        try
        {
            await BeginEdit();
        }
        catch (Exception ex)
        {
            ShowNotification($"Error loading tenant: {ex.Message}" , "error");
        }
    }

    private async Task BeginEdit()
    {
        if (TenantId == Guid.Empty)
        {
            // Get a new instance for creation - only Tenant Name and WhatsApp ID are enabled initially.
            _isEditingExisting = false;
            _whatsAppTenant = await _fdm.GetNew();
            ResetFieldEditability();
        }
        else
        {
            // Load existing tenant - all fields read-only (auto-filled from the database).
            _isEditingExisting = true;
            _whatsAppTenant = await _fdm.GetBy(TenantId);
            LockAllFields();
        }
    }

    private void ResetFieldEditability()
    {
        _canEditContactName = false;
        _canEditPhoneNumberId = false;
        _canEditBusinessAccountId = false;
        _canEditAccessToken = false;
        _waIdFound = false;
        _businessAccountFound = false;
    }

    private void LockAllFields()
    {
        _canEditContactName = false;
        _canEditPhoneNumberId = false;
        _canEditBusinessAccountId = false;
        _canEditAccessToken = false;
    }

    private void EnableNewContactFields()
    {
        _canEditContactName = true;
        _canEditPhoneNumberId = true;
        _canEditBusinessAccountId = true;
        _canEditAccessToken = false;
    }

    /// <summary>
    /// Triggered while typing in the WhatsApp ID field. Debounces briefly before fetching,
    /// so that once the user pauses it auto-fills the Contact and, when present, the linked
    /// WhatsApp Business Account credentials from the database.
    /// </summary>
    private async Task OnWaIdInput(ChangeEventArgs e)
    {
        if (_isEditingExisting)
            return;

        var waId = e?.Value?.ToString();
        _whatsAppTenant.Contact.WaId = waId;

        // Cancel any in-flight/pending lookup triggered by a previous partial value.
        _waIdSearchCts.Cancel();
        _waIdSearchCts.Dispose();
        var cts = _waIdSearchCts = new CancellationTokenSource();
        var token = cts.Token;

        try
        {
            // Debounce: wait for typing to pause before hitting the database.
            await Task.Delay(500 , token);
            await LookupAndApplyWaIdAsync(waId , token);
        }
        catch (OperationCanceledException)
        {
            // A newer keystroke superseded this lookup; ignore it.
        }
        catch (Exception ex)
        {
            ShowNotification($"Error checking WhatsApp ID: {ex.Message}" , "error");
        }
    }

    /// <summary>
    /// Triggered when the user leaves the WhatsApp ID field (safety net after on-input fetch).
    /// If the WhatsApp ID exists in the database, auto-fill and lock the linked
    /// Contact and WhatsApp Business Account fields; otherwise unlock them for entry.
    /// </summary>
    private async Task OnWaIdBlur()
    {
        if (_isEditingExisting)
            return;

        var waId = _whatsAppTenant?.Contact?.WaId;
        if (string.IsNullOrWhiteSpace(waId))
            return;

        try
        {
            await LookupAndApplyWaIdAsync(waId , CancellationToken.None);
        }
        catch (Exception ex)
        {
            ShowNotification($"Error checking WhatsApp ID: {ex.Message}" , "error");
        }
    }

    /// <summary>
    /// Looks up the given WhatsApp number in the database. If it exists and links to a
    /// WhatsApp tenant with credentials, auto-fills &amp; locks the Contact and WhatsApp
    /// Business Account fields. If it does not exist, unlocks the fields for manual entry.
    /// </summary>
    private async Task LookupAndApplyWaIdAsync(string waId , CancellationToken token)
    {
        if (string.IsNullOrWhiteSpace(waId))
        {
            _waIdFound = false;
            _businessAccountFound = false;
            EnableNewContactFields();
            return;
        }

        ContactVO contact = await _fdm.GetContactBy(waId.Trim());
        token.ThrowIfCancellationRequested();

        if (contact == null)
        {
            _waIdFound = false;
            _businessAccountFound = false;
            EnableNewContactFields();
        }
        else
        {
            _waIdFound = true;
            await AutoFillFromContact(contact , token);
        }
    }

    /// <summary>
    /// Auto-fills Contact and WhatsApp Business Account fields from an existing Contact record,
    /// fetching the linked credentials (Business Account ID + Access Token) when they exist.
    /// If the contact is present but has no usable linked credentials, the Business Account
    /// fields are unlocked so they can be entered manually.
    /// </summary>
    private async Task AutoFillFromContact(ContactVO contact , CancellationToken token)
    {
        _whatsAppTenant.Contact ??= new ContactVO();
        _whatsAppTenant.Contact.Name = contact.Name;
        _whatsAppTenant.Contact.PhoneNumberId = contact.PhoneNumberId;
        _whatsAppTenant.Contact.WaId = contact.WaId;

        // Resolve credentials from the linked WhatsApp tenant (if any).
        _whatsAppTenant.WhatsAppCredentials ??= new WhatsAppCredentialsVO();
        var linkedTenant = await _fdm.GetWhatsAppTenantByContact(contact);
        token.ThrowIfCancellationRequested();

        var hasCredentials = linkedTenant?.WhatsAppCredentials != null &&
            !string.IsNullOrEmpty(linkedTenant.WhatsAppCredentials.WABusinessAccountId);

        if (hasCredentials)
        {
            _whatsAppTenant.WhatsAppCredentials.WABusinessAccountId = linkedTenant.WhatsAppCredentials.WABusinessAccountId;
            _whatsAppTenant.WhatsAppCredentials.WAAccessToken = linkedTenant.WhatsAppCredentials.WAAccessToken;
            _businessAccountFound = true;
            LockAllFields();
        }
        else
        {
            // Contact exists but has no usable linked credentials yet - keep the contact
            // read-only but allow the Business Account ID / Access Token / Phone to be entered.
            _businessAccountFound = false;
            if (linkedTenant?.WhatsAppCredentials != null)
            {
                _whatsAppTenant.WhatsAppCredentials.WAAccessToken = linkedTenant.WhatsAppCredentials.WAAccessToken;
            }
            _canEditContactName = false;
            _canEditPhoneNumberId = true;
            _canEditBusinessAccountId = true;
            _canEditAccessToken = true;
        }
    }

    /// <summary>
    /// Triggered when the user leaves the Business Account ID field.
    /// If the Business Account ID exists in the database, auto-fill and lock the Access Token.
    /// </summary>
    private async Task OnBusinessAccountIdBlur()
    {
        if (_isEditingExisting)
            return;

        var businessAccountId = _whatsAppTenant?.WhatsAppCredentials?.WABusinessAccountId;
        if (string.IsNullOrWhiteSpace(businessAccountId))
            return;

        try
        {
            var credentials = await new WhatsAppCredentialsBE().GetWhatsAppCredentialsByBusinessAccountId(businessAccountId.Trim());
            if (credentials == null)
            {
                _businessAccountFound = false;
                _canEditAccessToken = true;
            }
            else
            {
                _businessAccountFound = true;
                _whatsAppTenant.WhatsAppCredentials ??= new WhatsAppCredentialsVO();
                _whatsAppTenant.WhatsAppCredentials.WAAccessToken = credentials.WAAccessToken;
                _canEditAccessToken = false;
            }
        }
        catch (Exception ex)
        {
            ShowNotification($"Error checking Business Account ID: {ex.Message}" , "error");
        }
    }

    private async Task HandleValidSubmit()
    {
        try
        {
            await EndEdit();
            NavManager.NavigateTo("/WhatsAppTenants");
        }
        catch (Exception ex)
        {
            ShowNotification($"Error saving tenant: {ex.Message}" , "error");
        }
    }

    private async Task EndEdit()
    {
        // Save using FDM
        await _fdm.Persist(_whatsAppTenant);
    }

    private void GoBack()
    {
        NavManager.NavigateTo("/WhatsAppTenants");
    }

    private void ToggleTokenVisibility() => showToken = !showToken;

    /// <summary>
    /// Whether the "Copy token &amp; URL" action is available. It is shown only when
    /// editing an existing tenant (an Id is present) that already has an API token.
    /// </summary>
    private bool CanCopyTenantToken =>
        _isEditingExisting &&
        !string.IsNullOrWhiteSpace(_whatsAppTenant?.Tenant?.Token);

    /// <summary>
    /// Copies the Brilliant WhatsApp endpoint URL together with the tenant API token
    /// to the clipboard as a JSON snippet for client-side configuration.
    /// </summary>
    private async Task CopyTenantToken()
    {
        if (!CanCopyTenantToken)
        {
            ShowNotification("No tenant token is available to copy." , "error");
            return;
        }

        try
        {
            string json = JsonSerializer.Serialize(new
            {
                BrilliantWhatsAppURL = "https://brilliantwhatsapp.brillianterp.app/",
                BrilliantToken = _whatsAppTenant.Tenant.Token
            });

            await JS.InvokeVoidAsync("copyTextToClipboard", json);
            ShowNotification("Tenant token and URL copied to clipboard." , "success");
        }
        catch (Exception ex)
        {
            ShowNotification($"Error copying: {ex.Message}" , "error");
        }
    }

    private void ShowNotification(string message , string type)
    {
        notificationMessage = message;
        notificationClass = type == "error" ? "error" : "success";
        StateHasChanged();
        Task.Delay(4000).ContinueWith(_ =>
        {
            notificationMessage = "";
            InvokeAsync(StateHasChanged);
        });
    }
}